### ISSUE TITLE
Move 2007+8 roundtables from archive.org to codex

### ISSUE THREAD

**Issue by gorlak** [TheToolsmiths/TheToolsmiths.github.io#1]

**Comment by VictorStepanov** [comment]
There are links to some of the old roundtable notes from the old Tool SIG wiki 
http://www.igda.org/wiki/GDC_2008_-_Tools_Roundtable_Notes_-_Friday
here:
https://github.com/TheToolsmiths/TheToolsmiths.github.io/blob/wiki/codex/gdc/roundtable/sessions.md

or are you talking about some other website on archive.org?
